title: NextPath Lab
email: [mguillau@bccrc.com]
description: >- 
  NextPath Lab Official Webpage.
baseurl: ""
url: "https://NextPath-Lab.github.io"
github_username: NextPath-Lab

theme: minima
plugins:
  - jekyll-feed

header_pages:
  - index.md
  - people/people_index.md
  - research/research_index.md
  - news.md
  - publications/pubs.md
  - software/software_index.md
